package token;

public enum Categoria {
    MAIN, VOID, FEC_PAR, ABR_PAR, ABR_CHA, FEC_CHA, ABR_COL, FEC_COL, VIRGULA, PON_VIR, ATRIBUICAO,
    IDENTIFICADOR, TIP_INT, TIP_FLO, TIP_BOO, TIP_CHA, TIP_STR, OPE_ADI, OPE_SUB, OPE_MUL,
    OPE_DIV, OPE_U_NEG, OPE_IGU, OPE_DIF, OPE_MEN, OPE_MAI, OPE_MEN_IGU, OPE_MAI_IGU, OPE_OU,
    OPE_E, OPE_NEG, OPE_CON, RETURN, IF, ELSE, FOR, IN, TO, STEP, WHILE, VAR, INPUT, OUTPUT,
    FUN, CONTINUE, BREAK, CON_INT, CON_FLO, CON_BOO, CON_STR, CON_INT_CAD, CON_FLO_CAD,
    CON_BOO_CAD, CON_CHA_CAD, CON_STR_CAD
}
